apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  enabled_plugins: |
      [rabbitmq_management]

  rabbitmq.conf: |
      default_vhost = /
      default_user = dev
      default_pass = test

      default_permissions.configure = .*
      default_permissions.read = .*
      default_permissions.write = .*
      default_user_tags.administrator = true
      default_user_tags.management = true
