apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    game: ueserver-svc
  name: ueserver-svc
spec:
  type: LoadBalancer
  ports:
    - name: "7778-udp"
      port: 7778
      protocol: UDP
      targetPort: 7778
    - name: "7779-udp"
      port: 7779
      protocol: UDP
      targetPort: 7779
    - name: "7780-udp"
      port: 7780
      protocol: UDP
      targetPort: 7780
  selector:
    game: ueserver
status:
  loadBalancer: {}
