apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: owspublicapi
  name: owspublicapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: owspublicapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: owspublicapi
    spec:
      containers:
        - image: public.ecr.aws/b6i2a6j1/futurecloud:owspublicapi-linux-latest
          imagePullPolicy: Always
          name: owspublicapi
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /app/appsettings.json
              subPath: appsettings.json
              name: owspublicapi-config
      restartPolicy: Always
      volumes:
        - name: owspublicapi-config
          configMap:
            name: owspublicapi-configmap
status: {}
