apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql-scripts
  namespace: default
data:
  setup.sql : |
    USE master
    GO

    IF DB_ID('OpenWorldServer') IS NULL
    BEGIN
      RESTORE DATABASE OpenWorldServer
      FROM DISK =  N'/var/opt/mssql/backups/OpenWorldServerEmpty.bak' WITH REPLACE,
        MOVE N'OpenWorldServer' TO N'/var/opt/mssql/data/OpenWorldServer.mdf',
        MOVE N'OpenWorldServer_log' TO  N'/var/opt/mssql/data/OpenWorldServer_log.ldf',
      NOUNLOAD,
      STATS = 5;
    END
    GO
  initialization.sh : |
    touch /var/opt/mssql/data/OpenWorldServer.mdf
    touch /var/opt/mssql/data/OpenWorldServer_log.ldf
    for i in {1..50};
    do
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P $SA_PASSWORD -d master -i setup.sql
      if [ $? -eq 0 ]
      then
          break
      else
          sleep 1
      fi
    done
  entrypoint.sh : |
    /user/config/initialization.sh & /opt/mssql/bin/sqlservr
  
