apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mssql
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mssql
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Developer
            - name: SA_PASSWORD
              value: yourStrong(!)Password
          image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
          name: mssql
          ports:
            - containerPort: 1433
          resources: {}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cd /user/config; ./initialization.sh"]
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssql-data
            - mountPath: /var/opt/mssql/log
              name: mssql-log
            - mountPath: /var/opt/mssql/secrets
              name: mssql-secrets
            - mountPath: /var/opt/mssql/backups
              name: mssql-backup
            - mountPath: /user/config
              name: mssql-scripts-vol
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command: ['sh', '-c']
          args:
            - wget -O /var/opt/mssql/backups/OpenWorldServerEmpty.bak http://192.168.35.2/aleria/OWS/.docker/mssql/backups/OpenWorldServerEmpty.bak;
          volumeMounts:
            - mountPath: /var/opt/mssql/backups
              name: mssql-backup
      restartPolicy: Always
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc-data
        - name: mssql-log
          persistentVolumeClaim:
            claimName: mssql-pvc-log
        - name: mssql-secrets
          persistentVolumeClaim:
            claimName: mssql-pvc-secrets
        - name: mssql-backup
          persistentVolumeClaim:
            claimName: mssql-pvc-backup
        - name: mssql-scripts-vol
          configMap:
            name: mssql-scripts
            defaultMode: 0744

status: {}
