apiVersion: v1
kind: ConfigMap
metadata:
  name: owscharacterpersistence-configmap
data:
  appsettings.json: |-
    {
    "Logging": {
        "LogLevel": {
        "Default": "Information",
        "Microsoft": "Warning",
        "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "AllowedHosts": "*",
    "RabbitMQOptions": {
        "RabbitMQHostName": "rabbitmq",
        "RabbitMQPort": 5672,
        "RabbitMQUserName": "dev",
        "RabbitMQPassword": "test"
    },
    "OWSAPIPathConfig": {
        "InternalPublicApiURL": "http://owspublicapi-svc:44302/",
        "InternalInstanceManagementApiURL": "http://owsinstancemanagement:44328/",
        "InternalCharacterPersistenceApiURL": "http://owscharacterpersistence:44323/"
    },
    "OWSStorageConfig": {
        "OWSDBConnectionString": "Server=mssql;Database=OpenWorldServer;User Id=SA;Password=yourStrong(!)Password;ConnectRetryCount=0"
    }
    }