apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: owsstatus
  name: owsstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: owsstatus
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: owsstatus
    spec:
      containers:
        - image: public.ecr.aws/b6i2a6j1/futurecloud:owsstatus-linux-latest
          imagePullPolicy: Always
          name: owsstatus
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /app/appsettings.json
              subPath: appsettings.json
              name: owsstatus-appsettings
              
      volumes:
        - name: owsstatus-appsettings
          configMap:
            name: owsstatus-configmap
      restartPolicy: Always
status: {}
